# Site settings
title: Filip Skogh
description: Filip Skogh
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fiskrt.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Filip Skogh
user_description: I'm currently doing thesis at Computer Vision Lab at ETHZ under Prof. Dr. Fisher Yu and Dr. Martin Danelljan. With the goal to develop a new unsupervised loss function for video object segmentation.
user_title: ML Intern<br>IBM Research ZÃ¼rich 
email: i@filipskogh.com
# twitter_username: 
#instagram_username: 
#facebook_username: 
linkedin_username: filipskogh
github_username:  fiskrt

#permalink: /blog/

exclude: ['blog/', 'package.json', 'node_modules', 'vendor']

